# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GermanGeoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('kind', models.CharField(choices=[(b'state', 'state'), (b'district', 'district'), (b'municipality', 'municipality'), (b'zipcode', 'zipcode')], max_length=255, verbose_name='Kind of Area')),
                ('rs', models.CharField(blank=True, max_length=255, verbose_name='Regional Key')),
                ('ags', models.CharField(blank=True, max_length=255, verbose_name='Official Municipality Key')),
                ('nuts', models.CharField(blank=True, max_length=255, verbose_name='NUTS key')),
                ('population', models.IntegerField(null=True)),
                ('area', models.FloatField(default=0.0, verbose_name='Area')),
                ('valid_on', models.DateTimeField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326, verbose_name='geometry')),
                ('part_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geogermany.GermanGeoArea', verbose_name='Part of')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
            ],
            options={
                'verbose_name': 'district',
                'proxy': True,
                'verbose_name_plural': 'districts',
            },
            bases=('geogermany.germangeoarea',),
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
            ],
            options={
                'verbose_name': 'municipality',
                'proxy': True,
                'verbose_name_plural': 'municipalities',
            },
            bases=('geogermany.germangeoarea',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
            ],
            options={
                'verbose_name': 'state',
                'proxy': True,
                'verbose_name_plural': 'states',
            },
            bases=('geogermany.germangeoarea',),
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
            ],
            options={
                'verbose_name': 'zipcode',
                'proxy': True,
                'verbose_name_plural': 'zipcodes',
            },
            bases=('geogermany.germangeoarea',),
        ),
    ]
