# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogermany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='germangeoarea',
            name='kind_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
