# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogermany', '0003_auto_20160525_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germangeoarea',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
