# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogermany', '0004_auto_20160525_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
            ],
            options={
                'verbose_name': 'borough',
                'proxy': True,
                'verbose_name_plural': 'boroughs',
            },
            bases=('geogermany.germangeoarea',),
        ),
        migrations.AlterField(
            model_name='germangeoarea',
            name='kind',
            field=models.CharField(choices=[(b'state', 'state'), (b'district', 'district'), (b'municipality', 'municipality'), (b'borough', 'borough'), (b'zipcode', 'zipcode')], max_length=255, verbose_name='Kind of Area'),
        ),
    ]
